[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"
exclude = ["migrations"]

[tool.ruff.lint]
select = ["E","F","I","B","UP","SIM"]
ignore = ["E203"]  # Compatible with Black

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["core"]
