openapi: 3.0.3
info:
  title: Ticket System API
  version: 0.1.0
  description: Multi-tenant ticketing API (header-scoped).
  contact:
    email: haptik.feedback@gmail.com
paths:
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/tickets:
    get:
      operationId: tickets_list
      parameters:
      - in: header
        name: X-Tenant-Slug
        schema:
          type: string
        description: Tenant slug (e.g., "acme"). Alternatively, send X-Tenant-ID (UUID).
        required: true
      tags:
      - tickets
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
          description: ''
    post:
      operationId: tickets_create
      parameters:
      - in: header
        name: X-Tenant-Slug
        schema:
          type: string
        description: Tenant slug (e.g., "acme"). Alternatively, send X-Tenant-ID (UUID).
        required: true
      tags:
      - tickets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ticket'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Ticket'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Ticket'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
          description: ''
  /api/tickets/{id}:
    get:
      operationId: tickets_retrieve
      parameters:
      - in: header
        name: X-Tenant-Slug
        schema:
          type: string
        description: Tenant slug (e.g., "acme"). Alternatively, send X-Tenant-ID (UUID).
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this ticket.
        required: true
      tags:
      - tickets
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
          description: ''
    put:
      operationId: tickets_update
      parameters:
      - in: header
        name: X-Tenant-Slug
        schema:
          type: string
        description: Tenant slug (e.g., "acme"). Alternatively, send X-Tenant-ID (UUID).
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this ticket.
        required: true
      tags:
      - tickets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ticket'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Ticket'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Ticket'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
          description: ''
    patch:
      operationId: tickets_partial_update
      parameters:
      - in: header
        name: X-Tenant-Slug
        schema:
          type: string
        description: Tenant slug (e.g., "acme"). Alternatively, send X-Tenant-ID (UUID).
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this ticket.
        required: true
      tags:
      - tickets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
          description: ''
    delete:
      operationId: tickets_destroy
      parameters:
      - in: header
        name: X-Tenant-Slug
        schema:
          type: string
        description: Tenant slug (e.g., "acme"). Alternatively, send X-Tenant-ID (UUID).
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this ticket.
        required: true
      tags:
      - tickets
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/tickets/{id}/complete:
    patch:
      operationId: tickets_complete_partial_update
      summary: Mark completed
      parameters:
      - in: header
        name: X-Tenant-Slug
        schema:
          type: string
        description: Tenant slug (e.g., "acme"). Alternatively, send X-Tenant-ID (UUID).
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this ticket.
        required: true
      tags:
      - tickets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
          description: ''
  /api/tickets/{id}/confirm:
    patch:
      operationId: tickets_confirm_partial_update
      summary: Mark ticket confirmed
      parameters:
      - in: header
        name: X-Tenant-Slug
        schema:
          type: string
        description: Tenant slug (e.g., "acme"). Alternatively, send X-Tenant-ID (UUID).
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this ticket.
        required: true
      tags:
      - tickets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
          description: ''
  /api/tickets/{id}/enroute:
    patch:
      operationId: tickets_enroute_partial_update
      summary: Mark technician enroute
      parameters:
      - in: header
        name: X-Tenant-Slug
        schema:
          type: string
        description: Tenant slug (e.g., "acme"). Alternatively, send X-Tenant-ID (UUID).
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this ticket.
        required: true
      tags:
      - tickets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
          description: ''
  /api/tickets/{id}/onsite:
    patch:
      operationId: tickets_onsite_partial_update
      summary: Mark technician onsite
      parameters:
      - in: header
        name: X-Tenant-Slug
        schema:
          type: string
        description: Tenant slug (e.g., "acme"). Alternatively, send X-Tenant-ID (UUID).
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this ticket.
        required: true
      tags:
      - tickets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
          description: ''
  /api/tickets/{id}/workstart:
    patch:
      operationId: tickets_workstart_partial_update
      summary: Work started
      parameters:
      - in: header
        name: X-Tenant-Slug
        schema:
          type: string
        description: Tenant slug (e.g., "acme"). Alternatively, send X-Tenant-ID (UUID).
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this ticket.
        required: true
      tags:
      - tickets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
          description: ''
  /api/tickets/{id}/workstop:
    patch:
      operationId: tickets_workstop_partial_update
      summary: Work stopped (pause)
      parameters:
      - in: header
        name: X-Tenant-Slug
        schema:
          type: string
        description: Tenant slug (e.g., "acme"). Alternatively, send X-Tenant-ID (UUID).
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this ticket.
        required: true
      tags:
      - tickets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTicket'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
          description: ''
components:
  schemas:
    PatchedTicket:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        at_risk:
          type: boolean
          readOnly: true
        title:
          type: string
          maxLength: 200
        description:
          type: string
        status:
          $ref: '#/components/schemas/StatusEnum'
        appointment_start:
          type: string
          format: date-time
          nullable: true
        appointment_end:
          type: string
          format: date-time
          nullable: true
        confirmed_at:
          type: string
          format: date-time
          nullable: true
        enroute_at:
          type: string
          format: date-time
          nullable: true
        onsite_at:
          type: string
          format: date-time
          nullable: true
        work_start_at:
          type: string
          format: date-time
          nullable: true
        work_stop_at:
          type: string
          format: date-time
          nullable: true
        completed_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        tenant:
          type: string
          format: uuid
          readOnly: true
        created_by:
          type: integer
          nullable: true
        assigned_to:
          type: integer
          nullable: true
    StatusEnum:
      enum:
      - created
      - routed
      - assigned
      - confirmed
      - enroute
      - onsite
      - workstart
      - workstop
      - completed
      type: string
      description: |-
        * `created` - Created
        * `routed` - Routed
        * `assigned` - Assigned
        * `confirmed` - Confirmed
        * `enroute` - EnRoute
        * `onsite` - OnSite
        * `workstart` - Work Start
        * `workstop` - Work Stop
        * `completed` - Completed
    Ticket:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        at_risk:
          type: boolean
          readOnly: true
        title:
          type: string
          maxLength: 200
        description:
          type: string
        status:
          $ref: '#/components/schemas/StatusEnum'
        appointment_start:
          type: string
          format: date-time
          nullable: true
        appointment_end:
          type: string
          format: date-time
          nullable: true
        confirmed_at:
          type: string
          format: date-time
          nullable: true
        enroute_at:
          type: string
          format: date-time
          nullable: true
        onsite_at:
          type: string
          format: date-time
          nullable: true
        work_start_at:
          type: string
          format: date-time
          nullable: true
        work_stop_at:
          type: string
          format: date-time
          nullable: true
        completed_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        tenant:
          type: string
          format: uuid
          readOnly: true
        created_by:
          type: integer
          nullable: true
        assigned_to:
          type: integer
          nullable: true
      required:
      - at_risk
      - created_at
      - id
      - tenant
      - title
      - updated_at
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
